import Link from 'next/link';
import { MfaSetup } from '@/components/mfa';
import { notFound,redirect } from 'next/navigation';
import { getViewer } from '@/lib/auth';
import { createSessionClient } from '@/lib/supabase/server';
import { PageTitle } from '@/components/ui';
import { DataTable } from '@/components/data-table';
import { EditorForm } from '@/components/editor-form';
import { ActionButton } from '@/components/forms';
const sections:Record<string,{label:string;table?:string;owner?:string;columns?:string[]}>= {overview:{label:'نظرة عامة'},auctions:{label:'مزاداتي',table:'auction_registrations',owner:'user_id',columns:['auction_id','status','created_at']},bids:{label:'مزايداتي',table:'bids',owner:'user_id',columns:['auction_id','amount_minor','sequence_no','accepted_at']},plates:{label:'لوحاتي',table:'plates',owner:'owner_id',columns:['digits','verification_status','listing_status','created_at']},favorites:{label:'المفضلة',table:'favorites',owner:'user_id',columns:['plate_id','created_at']},deposits:{label:'التأمينات',table:'payment_authorizations',owner:'user_id',columns:['auction_id','amount_minor','status','expires_at']},payments:{label:'المدفوعات',table:'payment_authorizations',owner:'user_id',columns:['id','status','captured_amount_minor','refunded_amount_minor']},notifications:{label:'الإشعارات',table:'notifications',owner:'user_id',columns:['title','body','created_at']},profile:{label:'الملف الشخصي'},security:{label:'الأمان'}};
export const metadata={title:'حسابي',robots:{index:false,follow:false}};
export default async function Account({params}:{params:Promise<{section?:string[]}>}){const user=await getViewer();if(!user)redirect('/login');const {section}=await params;const key=section?.[0]??'overview',config=sections[key];if(!config||(section?.length??0)>1)notFound();const db=await createSessionClient();const rows=config.table&&db?await db.from(config.table).select(config.columns!.join(',')).eq(config.owner!,user.id).limit(100):null;return <><PageTitle title={`أهلًا، ${user.displayName||'بك'}`} description="كل ما يخص لوحاتك ومزاداتك في مكان واحد."/><div className="container-fbs grid gap-7 py-10 lg:grid-cols-[220px_1fr]"><aside className="panel h-fit p-3"><nav aria-label="حسابي">{Object.entries(sections).map(([s,c])=><Link key={s} href={s==='overview'?'/account':`/account/${s}`} className={`mb-1 block rounded px-4 py-3 text-sm ${key===s?'bg-navy text-white':'hover:bg-paper'}`}>{c.label}</Link>)}</nav><div className="mt-4 border-t border-line pt-4"><ActionButton endpoint="/api/v1/auth/logout" label="تسجيل الخروج"/></div></aside><section className="min-w-0"><h2 className="mb-6 text-xl font-bold">{config.label}</h2>{key==='overview'?<div className="grid gap-5 sm:grid-cols-2"><Link href="/account/auctions" className="panel"><h3 className="mb-3 font-bold">تابع مزاداتك</h3><p className="text-sm leading-7 text-muted">راجع التسجيلات وحالة التأهيل والمزايدات.</p></Link><Link href="/sell-your-plate" className="panel"><h3 className="mb-3 font-bold">اعرض لوحة جديدة</h3><p className="text-sm leading-7 text-muted">قدّم بيانات اللوحة وارفع إثبات الملكية.</p></Link></div>:key==='profile'?<EditorForm endpoint="/api/v1/profile" fields={[{name:'displayName',label:'الاسم',value:user.displayName},{name:'phone',label:'الجوال بصيغة دولية',required:false}]}/>:key==='security'?<div className="panel"><p className="mb-5 text-sm leading-8">يمكنك تغيير كلمة المرور من خلال رابط آمن يصلك على بريدك الإلكتروني.</p><Link className="btn btn-navy" href="/forgot-password">استعادة كلمة المرور</Link><MfaSetup/></div>:rows?.error?<p role="alert">تعذر تحميل السجلات. أعد المحاولة لاحقًا.</p>:<DataTable rows={(rows?.data??[]) as unknown as Record<string,unknown>[]} columns={config.columns}/>}</section></div></>;}
