import { Receiver } from '@upstash/qstash';
import { z } from 'zod';
import { createAdminClient } from '@/lib/supabase/server';
import { failure,success } from '@/lib/api';
import { DomainError } from '@/lib/errors';
import { projectToRedis,realtimeProvider } from '@/modules/realtime/provider';
import type { AuctionSnapshot } from '@/modules/realtime/types';
export const maxDuration=60;
export async function POST(request:Request){try{const currentSigningKey=process.env.QSTASH_CURRENT_SIGNING_KEY,nextSigningKey=process.env.QSTASH_NEXT_SIGNING_KEY,site=process.env.NEXT_PUBLIC_SITE_URL;if(!currentSigningKey||!nextSigningKey||!site)throw new DomainError('SYSTEM_DEGRADED',undefined,{},503);const body=await request.text();const verified=await new Receiver({currentSigningKey,nextSigningKey}).verify({signature:request.headers.get('upstash-signature')??'',body,url:`${site}/api/v1/jobs`}).catch(()=>false);if(!verified)throw new DomainError('FORBIDDEN',undefined,{},401);const input=z.object({kind:z.enum(['outbox','finalize'])}).parse(JSON.parse(body));const db=createAdminClient();if(!db)throw new DomainError('SYSTEM_DEGRADED');if(input.kind==='finalize'){const {data,error}=await db.from('auctions').select('id').in('status',['LIVE','ENDING']).lte('effective_end_at',new Date().toISOString()).limit(25);if(error)throw error;let completed=0;for(const a of data??[]){const r=await db.rpc('fbs_finalize',{p_auction_id:a.id});if(r.error)throw r.error;completed++;}return success({completed});}const token=crypto.randomUUID();const {data,error}=await db.rpc('fbs_claim_outbox',{p_token:token});if(error)throw error;let completed=0;for(const item of (data??[]) as {id:string;aggregate_id:string;event_type:string;payload:AuctionSnapshot}[]){try{await projectToRedis(item.payload);await realtimeProvider().publish(item.aggregate_id,item.event_type,item.payload);const ack=await db.rpc('fbs_finish_outbox',{p_id:item.id,p_token:token,p_success:true});if(ack.error||!ack.data)throw new Error('ACK_FAILED');completed++;}catch{await db.rpc('fbs_finish_outbox',{p_id:item.id,p_token:token,p_success:false});}}return success({completed});}catch(e){return failure(e);}}
